site_name: Holiday Hack Challenge 2021 Writeup
site_url: https://hhc2021.agrohacksstuff.io
site_author: Dan Fedele
site_description: "Agr0 Dan's Holiday Hack Challenge Writeup for 2021!"
repo_url: "https://github.com/hhc2021writeup"

theme: mkdocs

# theme:
#   name: null
#   custom_dir: 'cinder'
#   hljs_languages:
#     - verilog
#     - ruby
#     - C
#     - json
#     - 

markdown_extensions:
  - admonition
  - codehilite
  - sane_lists
  - smarty

nav:
  - Home: 'index.md'
  - Objectives:
    - 7 - Printer Exploitation: 'obj7.md'
    - 10 - Now Hiring!: 'obj10.md'
    - 11 - Customer Complaint Analysis: 'obj11.md'
  - Terminals:
    - 1 - Wireless USB: 'term1.md'
    - 2 - Exif Metadata: 'term2.md'
    - 3 - Grepping for Gold: 'term3.md'
    - 5 - IPv6 Sandbox: 'term5.md'
    - 8 - HoHo...No: 'term8.md'
    - 10 - DuckyScript: 'term10.md'