site_name: Holiday Hack Challenge 2021 Writeup
site_url: https://hhc2021.agrohacksstuff.io
site_author: Dan Fedele
site_description: "Agr0 Dan's Holiday Hack Challenge Writeup for 2021!"
repo_url: "https://github.com/hhc2021writeup"

theme:
  name: material
  logo: img/santa.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark Mode
      primary: amber
      accent: amber
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Light Mode
      primary: blue
      accent: blue

plugins:
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'light' : 'dark'

extra_javascript:
  - extra/refresh_on_toggle_dark_light.js

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys

nav:
  - Home: 'index.md'
  # - Cast of Characters:

  - Objectives:
    - 1. Orientation: 'obj1.md'
    - 2. Where in the World is Caramel Santiago?: 'obj2.md'
    - 3. Thaw Frost Tower's Entrance: 'obj3.md'
    - 4. Slot Machine Investigation: 'obj4.md'
    - 5. Strange USB Device: 'obj5.md'
    - 6. Shellcode Primer:
      - Introduction: 'shellcode_primer/obj6-1.md'
      - Loops: 'shellcode_primer/obj6-2.md'
      - Getting Started: 'shellcode_primer/obj6-3.md'
      - Returning a Value: 'shellcode_primer/obj6-4.md'
      - System Calls: 'shellcode_primer/obj6-5.md'
      - Calling Into the Void: 'shellcode_primer/obj6-6.md'
      - Getting RIP: 'shellcode_primer/obj6-7.md'
      - Hello, World!: 'shellcode_primer/obj6-8.md'
      - Hello, World!!: 'shellcode_primer/obj6-9.md'
      - Opening a File: 'shellcode_primer/obj6-10.md'
      - Reading a File: 'shellcode_primer/obj6-11.md'
    - 7. Printer Exploitation: 'obj7.md'
    - 8. Kerberoasting on an Open Fire:
      - Introduction: 'kerberoasting/obj8-1.md'
      - Initial Foothold: 'kerberoasting/obj8-2.md'
      - Izzat you, AD Server?: 'kerberoasting/obj8-3.md'
      - LDAP Enumeration: 'kerberoasting/obj8-4.md'
      - RPC Enumeration: 'kerberoasting/obj8-5.md'
      - Let's Roast: 'kerberoasting/obj8-6.md'
      - Crackin dat Hash: 'kerberoasting/obj8-7.md'
      - Yaaarrrrr! (Time to Plunder): 'kerberoasting/obj8-8.md'
      - Pivoting Through the Snow: 'kerberoasting/obj8-9.md'
      - The Conclusion: 'kerberoasting/obj8-10.md'
    - 9. Splunk!: 'obj9.md'
    - 10. Now Hiring!: 'obj10.md'
    - 11. Customer Complaint Analysis: 'obj11.md'
    - 12. Frost Tower Website Checkup:
      - Introduction: 'frost_tower/obj12-1.md'
      - Recon Stage: 'frost_tower/obj12-2.md'
      - Discovering the Bypass: 'frost_tower/obj12-3.md'
      - SQL-Injecting my Way to the Top: 'frost_tower/obj12-4.md'
    - 13. FPGA Programming: 'obj13.md'
  - Terminals:
    - Exif Metadata: 'term_em.md'
    - Grepping for Gold: 'term_gfg.md'
    - Logic Munchers: 'term_lm.md'
    - IPv6 Sandbox: 'term_is.md'
    - Santa's Holiday Hero: 'term_shh.md'
    - HoHo...No: 'term_hhn.md'
    - Yara Analysis: 'term_ya.md'
    - IMDS Exploration: 'term_ie.md'
    - Strace Ltrace Retrace: 'term_slr.md'
    - The Elf Code:
      - How to Play: 'elf_code/term_tec_0.md'
      - Level 0: 'elf_code/term_tec_1.md'
      - Level 1: 'elf_code/term_tec_2.md'
      - Level 2: 'elf_code/term_tec_3.md'
      - Level 3: 'elf_code/term_tec_4.md'
      - Level 4: 'elf_code/term_tec_5.md'
      - Level 5: 'elf_code/term_tec_6.md'
      - Level 6: 'elf_code/term_tec_7.md'
      - Level 7: 'elf_code/term_tec_8.md'
      - Level 8: 'elf_code/term_tec_9.md'
      - Level 9: 'elf_code/term_tec_10.md'
      - Level 10: 'elf_code/term_tec_11.md'
    - Elevator Circuitry: 'term_ec.md'